/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.*;

/**
 *
 * @author rmiliano
 */
public class Form1inicio extends javax.swing.JFrame {

    /**
     * Creates new form Form1inicio
     */
    public Form1inicio() {
        initComponents();
        setLocationRelativeTo(null);
        /*this.comenzar.setEnabled(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comenzar = new javax.swing.JButton();
        reglamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 370));
        setSize(new java.awt.Dimension(640, 370));
        getContentPane().setLayout(null);

        comenzar.setText("Comenzar");
        comenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comenzarActionPerformed(evt);
            }
        });
        getContentPane().add(comenzar);
        comenzar.setBounds(450, 250, 87, 23);

        reglamento.setText("Reglamento");
        reglamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reglamentoActionPerformed(evt);
            }
        });
        getContentPane().add(reglamento);
        reglamento.setBounds(120, 250, 110, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cannon.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 150, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tanque1.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(510, 10, 110, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicioteg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, 4, 620, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comenzarActionPerformed
        Form2 f2 = new Form2();
        f2.setVisible(true);
        this.dispose();;
    }//GEN-LAST:event_comenzarActionPerformed

    private void reglamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reglamentoActionPerformed
        Form3 f3 = new Form3();
        f3.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_reglamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form1inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form1inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form1inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form1inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form1inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comenzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton reglamento;
    // End of variables declaration//GEN-END:variables
}
